-- Esquema completo (instalaciones nuevas). La app solo sincroniza payday_day; selected_period
-- queda como columna opcional (valor por defecto en BD). Si la tabla ya existia sin selected_period,
-- el ALTER siguiente la corrige; tambien puedes ejecutar supabase/migrations/20260427120000_add_selected_period.sql

create table if not exists public.finance_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  payday_day smallint not null default 1 check (payday_day between 1 and 31),
  selected_period text not null default to_char(now(), 'YYYY-MM'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.finance_settings
  add column if not exists selected_period text not null default to_char(now(), 'YYYY-MM');

create table if not exists public.finance_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  description text not null,
  amount numeric(12, 2) not null check (amount > 0),
  type text not null check (type in ('income', 'expense')),
  category text not null default 'General',
  period text not null,
  transaction_date date not null,
  created_at timestamptz not null default now()
);

alter table public.finance_settings enable row level security;
alter table public.finance_transactions enable row level security;

drop policy if exists "Users can read own settings" on public.finance_settings;
drop policy if exists "Users can insert own settings" on public.finance_settings;
drop policy if exists "Users can update own settings" on public.finance_settings;
drop policy if exists "Users can read own transactions" on public.finance_transactions;
drop policy if exists "Users can insert own transactions" on public.finance_transactions;
drop policy if exists "Users can update own transactions" on public.finance_transactions;
drop policy if exists "Users can delete own transactions" on public.finance_transactions;

create policy "Users can read own settings"
  on public.finance_settings for select
  using (auth.uid() = user_id);

create policy "Users can insert own settings"
  on public.finance_settings for insert
  with check (auth.uid() = user_id);

create policy "Users can update own settings"
  on public.finance_settings for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can read own transactions"
  on public.finance_transactions for select
  using (auth.uid() = user_id);

create policy "Users can insert own transactions"
  on public.finance_transactions for insert
  with check (auth.uid() = user_id);

create policy "Users can update own transactions"
  on public.finance_transactions for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own transactions"
  on public.finance_transactions for delete
  using (auth.uid() = user_id);

create index if not exists finance_transactions_user_date_idx
  on public.finance_transactions (user_id, transaction_date desc);

create table if not exists public.finance_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  period text not null,
  category text not null,
  amount numeric(12, 2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (user_id, period, category)
);

create index if not exists finance_budgets_user_period_idx
  on public.finance_budgets (user_id, period);

alter table public.finance_budgets enable row level security;

drop policy if exists "Users can read own budgets" on public.finance_budgets;
drop policy if exists "Users can insert own budgets" on public.finance_budgets;
drop policy if exists "Users can update own budgets" on public.finance_budgets;
drop policy if exists "Users can delete own budgets" on public.finance_budgets;

create policy "Users can read own budgets"
  on public.finance_budgets for select
  using (auth.uid() = user_id);

create policy "Users can insert own budgets"
  on public.finance_budgets for insert
  with check (auth.uid() = user_id);

create policy "Users can update own budgets"
  on public.finance_budgets for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own budgets"
  on public.finance_budgets for delete
  using (auth.uid() = user_id);
