-- Documentos justificantes asociados a gastos deducibles.
-- IMPORTANTE: antes de ejecutar, crea en Supabase > Storage > New bucket:
--   Nombre: deductible-docs   |   Tipo: Private
-- Luego crea estas políticas de storage en el SQL Editor:
--
-- create policy "Users upload own deductible docs" on storage.objects for insert
--   with check (bucket_id = 'deductible-docs' AND auth.uid()::text = (storage.foldername(name))[1]);
-- create policy "Users read own deductible docs" on storage.objects for select
--   using (bucket_id = 'deductible-docs' AND auth.uid()::text = (storage.foldername(name))[1]);
-- create policy "Users delete own deductible docs" on storage.objects for delete
--   using (bucket_id = 'deductible-docs' AND auth.uid()::text = (storage.foldername(name))[1]);

create table if not exists public.finance_deductible_docs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  transaction_id bigint not null references public.finance_transactions(id) on delete cascade,
  file_name text not null,
  file_path text not null,
  file_size bigint,
  mime_type text,
  created_at timestamptz not null default now()
);

create index if not exists finance_deductible_docs_transaction_idx
  on public.finance_deductible_docs (transaction_id);

alter table public.finance_deductible_docs enable row level security;

drop policy if exists "Users can read own deductible docs" on public.finance_deductible_docs;
drop policy if exists "Users can insert own deductible docs" on public.finance_deductible_docs;
drop policy if exists "Users can delete own deductible docs" on public.finance_deductible_docs;

create policy "Users can read own deductible docs"
  on public.finance_deductible_docs for select
  using (auth.uid() = user_id);

create policy "Users can insert own deductible docs"
  on public.finance_deductible_docs for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own deductible docs"
  on public.finance_deductible_docs for delete
  using (auth.uid() = user_id);
