-- Presupuestos de gasto por categoría y periodo (misma clave de periodo que movimientos).

create table if not exists public.finance_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  period text not null,
  category text not null,
  amount numeric(12, 2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  unique (user_id, period, category)
);

create index if not exists finance_budgets_user_period_idx
  on public.finance_budgets (user_id, period);

alter table public.finance_budgets enable row level security;

drop policy if exists "Users can read own budgets" on public.finance_budgets;
drop policy if exists "Users can insert own budgets" on public.finance_budgets;
drop policy if exists "Users can update own budgets" on public.finance_budgets;
drop policy if exists "Users can delete own budgets" on public.finance_budgets;

create policy "Users can read own budgets"
  on public.finance_budgets for select
  using (auth.uid() = user_id);

create policy "Users can insert own budgets"
  on public.finance_budgets for insert
  with check (auth.uid() = user_id);

create policy "Users can update own budgets"
  on public.finance_budgets for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own budgets"
  on public.finance_budgets for delete
  using (auth.uid() = user_id);
