-- Bancos / cuentas bancarias
create table if not exists public.finance_banks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now()
);

alter table public.finance_banks enable row level security;

drop policy if exists "Users can read own banks" on public.finance_banks;
drop policy if exists "Users can insert own banks" on public.finance_banks;
drop policy if exists "Users can update own banks" on public.finance_banks;
drop policy if exists "Users can delete own banks" on public.finance_banks;

create policy "Users can read own banks"
  on public.finance_banks for select
  using (auth.uid() = user_id);

create policy "Users can insert own banks"
  on public.finance_banks for insert
  with check (auth.uid() = user_id);

create policy "Users can update own banks"
  on public.finance_banks for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own banks"
  on public.finance_banks for delete
  using (auth.uid() = user_id);

-- Asociar transacciones a un banco (nullable, set null al borrar banco)
alter table public.finance_transactions
  add column if not exists bank_id bigint references public.finance_banks(id) on delete set null;
